import arijitsingh from "../ArtistPhoto/without back Arijit singh.png";
import badshah from "../ArtistPhoto/without background Badshah2.png";
import darshan from "../ArtistPhoto/darshan raval.png";
import honeySingh from "../ArtistPhoto/honey singh.png";
import himesh from "../ArtistPhoto/himesh rashmiya.png";
import neha from "../ArtistPhoto/Neha kakkar.png";

const MusicData = 
[
  {
    id : 1,
    artist : "arijit singh",
    photo : "https://static.toiimg.com/thumb/msid-53685247,width-1280,resizemode-4/53685247.jpg",
    artistPhoto : arijitsingh,
    about : "Arijit Singh is an Indian playback singer and music composer. The recipient of several accolades including a National Film Award and seven Filmfare Awards.",
    playLists:
      [
        {
          playlistId : 1,
          artistName : "arijit singh",
          songName : "bairiya",
          audio : "Arijit singh/Bairiya.mp3",
          songPoster : "https://c.saavncdn.com/297/Bairiya-Hindi-2023-20230314171414-500x500.jpg",
        },
        {
          playlistId : 2,
          artistName : "arijit singh",
          songName : "chaleya",
          audio : "Arijit singh/Chaleya.mp3",
          songPoster : "https://c.saavncdn.com/026/Chaleya-From-Jawan-Hindi-2023-20230814014337-500x500.jpg",
        },
        {
          playlistId : 3,
          artistName : "arijit singh",
          songName : "deva deva",
          audio : "Arijit singh/Deva Deva.mp3",
          songPoster : "https://c.saavncdn.com/044/Deva-Deva-From-Brahmastra-Hindi-2022-20220812225424-500x500.jpg",
        },
        {
          playlistId : 4,
          artistName : "arijit singh",
          songName : "heeriye",
          audio : "Arijit singh/Heeriye.mp3",
          songPoster : "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/b9/38/78/b93878fe-6c53-071d-0ffa-c5a5a9a1912e/cover.jpg/1200x630bb.jpg",
        },
        {
          playlistId : 5,
          artistName : "arijit singh",
          songName : "jhoome jo pathaan",
          audio : "Arijit singh/Jhoome Jo Pathaan.mp3",
          songPoster : "https://m.timesofindia.com/photo/96416857/size-167394/96416857.jpg",
        },
        {
          playlistId : 6,
          artistName : "arijit singh",
          songName : "kesariya",
          audio : "Arijit singh/Kesariya.mp3",
          songPoster : "https://lehren.com/wp-content/uploads/2022/09/Kesariya-Was-Reshot-After-Karan-Johar-Disapproval-Ayan-Mukerji-Shared-Original-Kesariya-Dance-Mix-Teaser.jpg",
        },
        {
          playlistId : 7,
          artistName : "arijit singh",
          songName : "khushi deke tumko",
          audio : "Arijit singh/Khushi Deke Tumko.mp3",
          songPoster : "https://i.ytimg.com/vi/7JaQPqf-X4Y/maxresdefault.jpg",
        },
        {
          playlistId : 8,
          artistName : "arijit singh",
          songName : "mere yaaraa",
          audio : "Arijit singh/Mere Yaaraa.mp3",
          songPoster : "https://i.ytimg.com/vi/AS2HDpacBek/maxresdefault.jpg",
        },
        {
          playlistId : 9,
          artistName : "arijit singh",
          songName : "tere pyar mein",
          audio : "Arijit singh/Tere Pyar Mein.mp3",
          songPoster : "https://i.ytimg.com/vi/SzSQMfZJ3HE/maxresdefault.jpg",
        },
        {
          playlistId : 10,
          artistName : "arijit singh",
          songName : "tu hai to mujhe",
          audio : "Arijit singh/Tu Hai To Mujhe Phir Aur Kya Chahiye.mp3",
          songPoster : "https://i.ytimg.com/vi/PhjuxZsbK-A/maxresdefault.jpg",
        },
      ],
    popularSongs :   
      [
        {
          popularsongId : 1,
          artistName : "arijit singh",
          songName : "baaton ko teri",
          audio : "Arijit singh/ArijitPopularSong/Baaton Ko Teri.mp3",
          songPoster : "https://c.saavncdn.com/768/All-Is-Well-Hindi-2015-500x500.jpg",
        },
        {
          popularsongId : 2,
          artistName : "arijit singh",
          songName : "bekhayali",
          audio : "Arijit singh/ArijitPopularSong/Bekhayali.mp3",
          songPoster : "https://c.saavncdn.com/608/Bekhayali-From-Kabir-Singh--Hindi-2019-20190524024538-500x500.jpg",
        },
        {
          popularsongId : 3,
          artistName : "arijit singh",
          songName : "chahun main ya naa",
          audio : "Arijit singh/ArijitPopularSong/Chahun Main Ya Naa.mp3",
          songPoster : "https://s1.dmcdn.net/v/BkA761M5x3GFN0kqx/x1080",
        },
        {
          popularsongId : 4,
          artistName : "arijit singh",
          songName : "channa mereya",
          audio : "Arijit singh/ArijitPopularSong/Channa Mereya.mp3",
          songPoster : "https://c.saavncdn.com/103/Channa-Mereya-From-Ae-Dil-Hai-Mushkil-Hindi-2016-500x500.jpg",
        },
        {
          popularsongId : 5,
          artistName : "arijit singh",
          songName : "dil cheez tujhe dedi",
          audio : "Arijit singh/ArijitPopularSong/Dil Cheez Tujhe Dedi.mp3",
          songPoster : "https://i.ytimg.com/vi/0m2xS08lTbE/maxresdefault.jpg",
        },
        {
          popularsongId : 6,
          artistName : "arijit singh",
          songName : "fitoor",
          audio : "Arijit singh/ArijitPopularSong/Fitoor.mp3",
          songPoster : "https://m.media-amazon.com/images/I/81Qnj5acMRL._AC_UF1000,1000_QL80_.jpg",
        },
        {
          popularsongId : 7,
          artistName : "arijit singh",
          songName : "ghungroo",
          audio : "Arijit singh/ArijitPopularSong/Ghungroo.mp3",
          songPoster : "https://a10.gaanacdn.com/images/albums/95/3155895/crop_480x480_1588055035_3155895.jpg",
        },
        {
          popularsongId : 8,
          artistName : "arijit singh",
          songName : "keu jaane naa",
          audio : "Arijit singh/ArijitPopularSong/Keu Jaane Naa.mp3",
          songPoster : "https://i.ytimg.com/vi/acuERA8BueM/maxresdefault.jpg",
        },
        {
          popularsongId : 9,
          artistName : "arijit singh",
          songName : "khairiyat",
          audio : "Arijit singh/ArijitPopularSong/Khairiyat.mp3",
          songPoster : "https://m.media-amazon.com/images/M/MV5BN2Y0YjJkMTctNjNmMC00MDkyLTkzZDktMWZmNTdmN2YyNWNmXkEyXkFqcGdeQXVyMTA5NzIyMDY5._V1_.jpg",
        },
        {
          popularsongId : 10,
          artistName : "arijit singh",
          songName : "leke prabhu ka naam",
          audio : "Arijit singh/ArijitPopularSong/Leke Prabhu Ka Naam.mp3",
          songPoster : "https://i.ytimg.com/vi/1Yzi3CbbqJ0/maxresdefault.jpg",
        },
        {
          popularsongId : 11,
          artistName : "arijit singh",
          songName : "maan le",
          audio : "Arijit singh/ArijitPopularSong/Maan Le.mp3",
          songPoster : "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/5d/51/3b/5d513b1d-23bc-07be-79f4-54d917557d59/196589115713.jpg/1200x1200bb.jpg",
        },
        {
          popularsongId : 12,
          artistName : "arijit singh",
          songName : "o desh mere",
          audio : "Arijit singh/ArijitPopularSong/O Desh Mere.mp3",
          songPoster : "https://i.ytimg.com/vi/I0-IiiVgvyU/maxresdefault.jpg",
        },
        {
          popularsongId : 13,
          artistName : "arijit singh",
          songName : "ruaan",
          audio : "Arijit singh/ArijitPopularSong/Ruaan.mp3",
          songPoster : "https://c.saavncdn.com/487/Ruaan-From-Tiger-3-Hindi-2023-20231106115814-500x500.jpg",
        },
        {
          popularsongId : 14,
          artistName : "arijit singh",
          songName : "tera chehra jab",
          audio : "Arijit singh/ArijitPopularSong/Tera Chehra Jab.mp3",
          songPoster : "https://img.youtube.com/vi/aKW4s-0EH9o/maxresdefault.jpg",
        },
        {
          popularsongId : 15,
          artistName : "arijit singh",
          songName : "tere naam dhokha rakh du",
          audio : "Arijit singh/ArijitPopularSong/Tere Naam Dhokha Rakh Du.mp3",
          songPoster : "https://i.ytimg.com/vi/-hqudO6BEHA/sddefault.jpg",
        },
        {
          popularsongId : 16,
          artistName : "arijit singh",
          songName : "tere sang",
          audio : "Arijit singh/ArijitPopularSong/Tere Sang.mp3",
          songPoster : "https://c.saavncdn.com/046/Tere-Sang-From-Satellite-Shankar--Hindi-2019-20191031125322-500x500.jpg",
        },
        {
          popularsongId : 17,
          artistName : "arijit singh",
          songName : "tu hi yaar mera",
          audio : "Arijit singh/ArijitPopularSong/Tu Hi Yaar Mera.mp3",
          songPoster : "https://c.saavncdn.com/258/Tu-Hi-Yaar-Mera-From-Pati-Patni-Aur-Woh--Hindi-2019-20191202231535-500x500.jpg",
        },
        {
          popularsongId : 18,
          artistName : "arijit singh",
          songName : "tujhe kitna chahne lage",
          audio : "Arijit singh/ArijitPopularSong/Tujhe Kitna Chahne Lage.mp3",
          songPoster : "https://c.saavncdn.com/763/Tujhe-Kitna-Chahne-Lage-From-Kabir-Singh--Hindi-2019-20190531075012-500x500.jpg",
        },
        {
          popularsongId : 19,
          artistName : "arijit singh",
          songName : "tumi je sesh tumi suru",
          audio : "Arijit singh/ArijitPopularSong/Tumi Je Sesh Tumi Suru.mp3",
          songPoster : "https://thumb.mp3jio.com/thumb/c/7934_3.jpg",
        },
        {
          popularsongId : 20,
          artistName : "arijit singh",
          songName : "woh din",
          audio : "Arijit singh/ArijitPopularSong/Woh Din.mp3",
          songPoster : "https://c.saavncdn.com/439/Woh-Din-From-Chhichhore--Hindi-2019-20190826130140-500x500.jpg",
        },
      ]
  },

  {
    id : 2,
    artist : "Badshah",
    photo : "https://m.economictimes.com/thumb/height-450,width-600,imgsize-108704,msid-65468032/badshah.jpg",
    artistPhoto : badshah,
    about : "Aditya Prateek Singh Sisodia, known professionally as Badshah, is an Indian rapper and singer. He is known for his Indian pop, hip-hop, rap, synthwave, underground rap, pop rap, hardcore rap and freestyle music.",
    playLists:
      [
        {
          playlistId : 1,
          artistName : "badshah",
          songName : "dj waley babu",
          audio : "Badshah/Dj Waley Babu.mp3",
          songPoster : "https://i.ytimg.com/vi/0hy5fz7ye7k/maxresdefault.jpg",
        },
        {
          playlistId : 2,
          artistName : "badshah",
          songName : "garmi",
          audio : "Badshah/Garmi.mp3",
          songPoster : "https://i.ytimg.com/vi/IE8OD5FbU-c/maxresdefault.jpg",
        },
        {
          playlistId : 3,
          artistName : "badshah",
          songName : "genda phool",
          audio : "Badshah/Genda Phool.mp3",
          songPoster : "https://m.timesofindia.com/photo/74824833/size-266647/74824833.jpg",
        },
        {
          playlistId : 4,
          artistName : "badshah",
          songName : "gone girl",
          audio : "Badshah/Gone Girl.mp3",
          songPoster : "https://i.ytimg.com/vi/Z0C3oLWMUqE/maxresdefault.jpg",
        },
        {
          playlistId : 5,
          artistName : "badshah",
          songName : "jugnu",
          audio : "Badshah/Jugnu.mp3",
          songPoster : "https://i.ytimg.com/vi/ksY3wb4vtlA/maxresdefault.jpg",
        },
        {
          playlistId : 6,
          artistName : "badshah",
          songName : "munna badnaam hua",
          audio : "Badshah/Munna Badnaam Hua.mp3",
          songPoster : "https://i.ytimg.com/vi/889Eg3d3Bys/maxresdefault.jpg",
        },
        {
          playlistId : 7,
          artistName : "badshah",
          songName : "paagal",
          audio : "Badshah/Paagal.mp3",
          songPoster : "https://www.quirkybyte.com/wp-content/uploads/2019/08/1-39.jpg",
        },
        {
          playlistId : 8,
          artistName : "badshah",
          songName : "paani paani",
          audio : "Badshah/Paani Paani.mp3",
          songPoster : "https://m.media-amazon.com/images/M/MV5BYTQ3OTgwMzQtN2I0NC00YWU5LTliYmYtMmI4YmYzMjI2NDk3XkEyXkFqcGdeQXVyODAzNzAwOTU@._V1_FMjpg_UX1000_.jpg",
        },
        {
          playlistId : 9,
          artistName : "badshah",
          songName : "sajna",
          audio : "Badshah/Sajna.mp3",
          songPoster : "https://i.ytimg.com/vi/YSWpWmu_zvE/maxresdefault.jpg",
        },
        {
          playlistId : 10,
          artistName : "badshah",
          songName : "slow slow",
          audio : "Badshah/Slow Slow.mp3",
          songPoster : "https://i.ytimg.com/vi/ToWapzm8SiY/maxresdefault.jpg",
        },
      ],
    popularSongs :   
      [
        {
          popularsongId : 1,
          artistName : "badshah",
          songName : "feel hai",
          audio : "Badshah/BadshahPopularSong/Feel Hai.mp3",
          songPoster : "https://i.ytimg.com/vi/bDgsMwXcTkk/maxresdefault.jpg",
        },
        {
          popularsongId : 2,
          artistName : "badshah",
          songName : "haryana roadways",
          audio : "Badshah/BadshahPopularSong/Haryana Roadways.mp3",
          songPoster : "https://p16-tm-sg.tiktokmusic.me/img/tos-alisg-v-2102/f72f91d1993040b6ba3422d543ac6219~c5_500x500.jpg",
        },
        {
          popularsongId : 3,
          artistName : "badshah",
          songName : "heelein toot gayi",
          audio : "Badshah/BadshahPopularSong/Heelein Toot Gayi.mp3",
          songPoster : "https://i.ytimg.com/vi/Pm-ssssVk9w/maxresdefault.jpg",
        },
        {
          popularsongId : 4,
          artistName : "badshah",
          songName : "hot launde",
          audio : "Badshah/BadshahPopularSong/Hot Launde.mp3",
          songPoster : "https://i.ytimg.com/vi/iuqfU9Ll300/maxresdefault.jpg",
        },
        {
          popularsongId : 5,
          artistName : "badshah",
          songName : "issa vibe",
          audio : "Badshah/BadshahPopularSong/Issa Vibe.mp3",
          songPoster : "https://i.ytimg.com/vi/E0IXjLRDSrg/maxresdefault.jpg",
        },
        {
          popularsongId : 6,
          artistName : "badshah",
          songName : "kamaal",
          audio : "Badshah/BadshahPopularSong/Kamaal.mp3",
          songPoster : "https://m.timesofindia.com/photo/72437784/size-178432/72437784.jpg",
        },
        {
          popularsongId : 7,
          artistName : "badshah",
          songName : "kar gayi chull",
          audio : "Badshah/BadshahPopularSong/Kar Gayi Chull.mp3",
          songPoster : "https://2.bp.blogspot.com/-EKlZbtjn0vQ/VuPBXSRPxSI/AAAAAAAABA4/hJLXzMENFgsVoQKmB8tmqM72iOQ70Hy2w/s1600/maxresdefault.jpg",
        },
        {
          popularsongId : 8,
          artistName : "badshah",
          songName : "lets nacho",
          audio : "Badshah/BadshahPopularSong/Lets Nacho.mp3",
          songPoster : "https://i.pinimg.com/originals/88/cb/c4/88cbc4744495ddf8256d90fa3e0e13a6.jpg",
        },
        {
          popularsongId : 9,
          artistName : "badshah",
          songName : "nasha",
          audio : "Badshah/BadshahPopularSong/Nasha.mp3",
          songPoster : "https://i.ytimg.com/vi/Gtx-oZtQ32E/maxresdefault.jpg",
        },
        {
          popularsongId : 10,
          artistName : "badshah",
          songName : "players",
          audio : "Badshah/BadshahPopularSong/Players.mp3",
          songPoster : "https://i.ytimg.com/vi/CeFQO9MQNqs/maxresdefault.jpg",
        },
        {
          popularsongId : 11,
          artistName : "badshah",
          songName : "proper patola",
          audio : "Badshah/BadshahPopularSong/Proper Patola.mp3",
          songPoster : "https://i.ytimg.com/vi/pQOoFEBF4R8/maxresdefault.jpg",
        },
        {
          popularsongId : 12,
          artistName : "badshah",
          songName : "saans toh le le",
          audio : "Badshah/BadshahPopularSong/Saans Toh Le Le.mp3",
          songPoster : "https://i.ytimg.com/vi/bXfggC0jrrc/maxresdefault.jpg",
        },
        {
          popularsongId : 13,
          artistName : "badshah",
          songName : "sab gazab",
          audio : "Badshah/BadshahPopularSong/Sab Gazab.mp3",
          songPoster : "https://i.ytimg.com/vi/2yXzvjb60Uw/maxresdefault.jpg",
        },
        {
          popularsongId : 14,
          artistName : "badshah",
          songName : "saturday saturday",
          audio : "Badshah/BadshahPopularSong/Saturday Saturday.mp3",
          songPoster : "https://i.ytimg.com/vi/uOSinF3TKVE/maxresdefault.jpg",
        },
        {
          popularsongId : 15,
          artistName : "badshah",
          songName : "she is on fire",
          audio : "Badshah/BadshahPopularSong/She Is On Fire.mp3",
          songPoster : "https://i.ytimg.com/vi/PfbwYiBTeAo/maxresdefault.jpg",
        },
        {
          popularsongId : 16,
          artistName : "badshah",
          songName : "sheher ki ladki",
          audio : "Badshah/BadshahPopularSong/Sheher Ki Ladki.mp3",
          songPoster : "https://i.ytimg.com/vi/H0cxlRsTInY/maxresdefault.jpg",
        },
        {
          popularsongId : 17,
          artistName : "badshah",
          songName : "shuru",
          audio : "Badshah/BadshahPopularSong/Shuru.mp3",
          songPoster : "https://i.pinimg.com/564x/c4/72/69/c47269b58b94e72c2295a9099873da2a.jpg",
        },
        {
          popularsongId : 18,
          artistName : "badshah",
          songName : "tabahi",
          audio : "Badshah/BadshahPopularSong/Tabahi.mp3",
          songPoster : "https://static.toiimg.com/thumb/msid-90115423,width-1280,resizemode-4/90115423.jpg",
        },
        {
          popularsongId : 19,
          artistName : "badshah",
          songName : "too many",
          audio : "Badshah/BadshahPopularSong/Too Many.mp3",
          songPoster : "https://i.ytimg.com/vi/kuiL4WNWf3w/maxresdefault.jpg",
        },
        {
          popularsongId : 20,
          artistName : "badshah",
          songName : "top tucker uchana",
          audio : "Badshah/BadshahPopularSong/Top Tucker Uchana.mp3",
          songPoster : "https://m.timesofindia.com/photo/80877555/size-232175/80877555.jpg",
        },
      ]
  },

  {
    id : 3,
    artist : "Darshan Raval",
    photo : "https://static.toiimg.com/photo/82598111.cms",
    artistPhoto : darshan,
    about : "Darshan Raval is an Indian singer, composer, and songwriter. He is known for his work in different languages including Hindi, Gujarati, Punjabi and Bengali.",
    playLists:
      [
        {
          playlistId : 1,
          artistName : "darshan raval",
          songName : "aa jaana",
          audio : "Darshan Raval/Aa Jaana.mp3",
          songPoster : "https://m.timesofindia.com/photo/72956284/size-169615/72956284.jpg",
        },
        {
          playlistId : 2,
          artistName : "darshan raval",
          songName : "asal mein",
          audio : "Darshan Raval/Asal Mein.mp3",
          songPoster : "https://m.media-amazon.com/images/M/MV5BYmQ0MTE3ZjYtZGEyMS00NzBmLTkxNzMtMTI0MDYwZGE3NzYxXkEyXkFqcGdeQXVyMTA5NzIyMDY5._V1_.jpg",
        },
        {
          playlistId : 3,
          artistName : "darshan raval",
          songName : "baarish lete aana 2.0",
          audio : "Darshan Raval/Baarish Lete Aana 2.0.mp3",
          songPoster : "https://i.ytimg.com/vi/sY6fitmZy5A/maxresdefault.jpg",
        },
        {
          playlistId : 4,
          artistName : "darshan raval",
          songName : "baarishon mein",
          audio : "Darshan Raval/Baarishon Mein.mp3",
          songPoster : "https://pagalnew.com/coverimages/Baarishon-Mein-Darshan-Raval-500-500.jpg",
        },
        {
          playlistId : 5,
          artistName : "darshan raval",
          songName : "barsaat",
          audio : "Darshan Raval/Barsaat.mp3",
          songPoster : "https://i.ytimg.com/vi/hjpUcOs_nsg/maxresdefault.jpg",
        },
        {
          playlistId : 6,
          artistName : "darshan raval",
          songName : "bekhudi",
          audio : "Darshan Raval/Bekhudi.mp3",
          songPoster : "https://i.ytimg.com/vi/s_l1hWwPbnk/sddefault.jpg",
        },
        {
          playlistId : 7,
          artistName : "darshan raval",
          songName : "bhula diya",
          audio : "Darshan Raval/Bhula Diya.mp3",
          songPoster : "https://static.toiimg.com/thumb/msid-67883576,width-1280,resizemode-4/67883576.jpg",
        },
        {
          playlistId : 8,
          artistName : "darshan raval",
          songName : "bhula dunga",
          audio : "Darshan Raval/Bhula Dunga.mp3",
          songPoster : "https://static.toiimg.com/thumb/msid-74790103,width-1280,resizemode-4/74790103.jpg",
        },
        {
          playlistId : 9,
          artistName : "darshan raval",
          songName : "chogada",
          audio : "Darshan Raval/Chogada.mp3",
          songPoster : "https://i.ytimg.com/vi/asYxxtiWUyw/maxresdefault.jpg",
        },
        {
          playlistId : 10,
          artistName : "darshan raval",
          songName : "dhindhora baje re",
          audio : "Darshan Raval/Dhindhora Baje Re.mp3",
          songPoster : "https://www.pianodaddy.com/sttorage/2023/08/Dhindhora-Baje-Re-Piano-Notes.jpg",
        },
      ],
    popularSongs :   
      [
        {
          popularsongId : 1,
          artistName : "darshan raval",
          songName : "dhol bajaa",
          audio : "Darshan Raval/DarshanPopularSong/Dhol Bajaa.mp3",
          songPoster : "https://ostpk.com/wp-content/uploads/2022/09/Dhol-Bajaa-Lyrics-Darshan-Raval-Prakriti-Giri-Wo-Lyrics.jpg",
        },
        {
          popularsongId : 2,
          artistName : "darshan raval",
          songName : "dil badnaam",
          audio : "Darshan Raval/DarshanPopularSong/Dil Badnaam.mp3",
          songPoster : "https://i.ytimg.com/vi/BzOrVRToPSg/sddefault.jpg",
        },
        {
          popularsongId : 3,
          artistName : "darshan raval",
          songName : "dil hai deewana",
          audio : "Darshan Raval/DarshanPopularSong/Dil Hai Deewana.mp3",
          songPoster : "https://i.ytimg.com/vi/o8-cgi6FSHU/maxresdefault.jpg",
        },
        {
          popularsongId : 4,
          artistName : "darshan raval",
          songName : "dil julaha",
          audio : "Darshan Raval/DarshanPopularSong/Dil Julaha.mp3",
          songPoster : "https://i.ytimg.com/vi/4z408skANFU/maxresdefault.jpg",
        },
        {
          popularsongId : 5,
          artistName : "darshan raval",
          songName : "dil mera",
          audio : "Darshan Raval/DarshanPopularSong/Dil Mera.mp3",
          songPoster : "https://media.lyricsmint.com/photos/10492/maxresdefault_cover.jpg",
        },
        {
          popularsongId : 6,
          artistName : "darshan raval",
          songName : "duniya chhor doon",
          audio : "Darshan Raval/DarshanPopularSong/Duniya Chhor Doon.mp3",
          songPoster : "https://i.ytimg.com/vi/hsICZS0K3xU/maxresdefault.jpg",
        },
        {
          popularsongId : 7,
          artistName : "darshan raval",
          songName : "ek tarfa",
          audio : "Darshan Raval/DarshanPopularSong/Ek Tarfa.mp3",
          songPoster : "https://i.ytimg.com/vi/hi0301FRL3g/maxresdefault.jpg",
        },
        {
          popularsongId : 8,
          artistName : "darshan raval",
          songName : "faasla",
          audio : "Darshan Raval/DarshanPopularSong/Faasla.mp3",
          songPoster : "https://i.ytimg.com/vi/llsOfL-aoBs/maxresdefault.jpg",
        },
        {
          popularsongId : 9,
          artistName : "darshan raval",
          songName : "goriye",
          audio : "Darshan Raval/DarshanPopularSong/Goriye.mp3",
          songPoster : "https://i.ytimg.com/vi/HmESsvTPQPk/maxresdefault.jpg",
        },
        {
          popularsongId : 10,
          artistName : "darshan raval",
          songName : "haaye dard",
          audio : "Darshan Raval/DarshanPopularSong/Haaye Dard.mp3",
          songPoster : "https://i.ytimg.com/vi/mjcHc8l_5k8/hqdefault.jpg",
        },
        {
          popularsongId : 11,
          artistName : "darshan raval",
          songName : "hawa banke",
          audio : "Darshan Raval/DarshanPopularSong/Hawa Banke.mp3",
          songPoster : "https://i.ytimg.com/vi/WAD0jRRnD8M/maxresdefault.jpg",
        },
        {
          popularsongId : 12,
          artistName : "darshan raval",
          songName : "jab tum chaho",
          audio : "Darshan Raval/DarshanPopularSong/Jab Tum Chaho.mp3",
          songPoster : "https://s2.dmcdn.net/v/BzTof1MCXjDQfx0vX/x1080",
        },
        {
          popularsongId : 13,
          artistName : "darshan raval",
          songName : "jannat ve",
          audio : "Darshan Raval/DarshanPopularSong/Jannat Ve.mp3",
          songPoster : "https://i.ytimg.com/vi/m-HVT9FsJDI/mqdefault.jpg",
        },
        {
          popularsongId : 14,
          artistName : "darshan raval",
          songName : "kaash aisa hota",
          audio : "Darshan Raval/DarshanPopularSong/Kaash Aisa Hota.mp3",
          songPoster : "https://www.quirkybyte.com/wp-content/uploads/2019/04/kash-aisa-hota-by-darshan-mp3-downloa.jpg",
        },
        {
          popularsongId : 15,
          artistName : "darshan raval",
          songName : "kabhii tumhhe",
          audio : "Darshan Raval/DarshanPopularSong/Kabhii Tumhhe.mp3",
          songPoster : "https://timesofindia.indiatimes.com/photo/msid-85455352,imgsize-173702.cms",
        },
        {
          popularsongId : 16,
          artistName : "darshan raval",
          songName : "lo aayi barsaat",
          audio : "Darshan Raval/DarshanPopularSong/Lo Aayi Barsaat.mp3",
          songPoster : "https://www.lyricsgoal.com/wp-content/uploads/2023/07/lo-aayi-barsaat-darshan-raval.jpg",
        },
        {
          popularsongId : 17,
          artistName : "darshan raval",
          songName : "maa",
          audio : "Darshan Raval/DarshanPopularSong/Maa.mp3",
          songPoster : "https://www.surilegeet.com/wp-content/uploads/2020/10/Maa-lyrics-darshan-raval.jpg",
        },
        {
          popularsongId : 18,
          artistName : "darshan raval",
          songName : "mahiye jinna sohna",
          audio : "Darshan Raval/DarshanPopularSong/Mahiye Jinna Sohna.mp3",
          songPoster : "https://i.pinimg.com/originals/02/f3/11/02f3118c1076088b0d768fde3fc14160.jpg",
        },
        {
          popularsongId : 19,
          artistName : "darshan raval",
          songName : "mujhe peene do",
          audio : "Darshan Raval/DarshanPopularSong/Mujhe Peene Do.mp3",
          songPoster : "https://i.ytimg.com/vi/SCyyjXFQRgE/maxresdefault.jpg",
        },
        {
          popularsongId : 20,
          artistName : "darshan raval",
          songName : "phir mohabbat",
          audio : "Darshan Raval/DarshanPopularSong/Phir Mohabbat.mp3",
          songPoster : "https://i.ytimg.com/vi/T_nS9FT2mpM/maxresdefault.jpg",
        },
      ]
  },

  {
    id : 4,
    artist : "Honey Singh",
    photo : "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2016/08/honey-singh-1471937186.jpg",
    artistPhoto : honeySingh,
    about : "Hirdesh Singh, known professionally as Yo Yo Honey Singh, or simply Honey Singh, is an Indian rapper, singer, music producer, and actor.",
    playLists:
      [
        {
          playlistId : 1,
          artistName : "honey singh",
          songName : "aankhon aankhon",
          audio : "Honey Singh/Aankhon Aankhon.mp3",
          songPoster : "https://i.ytimg.com/vi/AtYqQksCR3A/maxresdefault.jpg",
        },
        {
          playlistId : 2,
          artistName : "honey singh",
          songName : "aata majhi satakli",
          audio : "Honey Singh/Aata Majhi Satakli.mp3",
          songPoster : "https://i.ytimg.com/vi/M3KqzpP6Ej0/maxresdefault.jpg",
        },
        {
          playlistId : 3,
          artistName : "honey singh",
          songName : "angreji beat",
          audio : "Honey Singh/Angreji Beat.mp3",
          songPoster : "https://i.ytimg.com/vi/Du6Xi5M7D-g/maxresdefault.jpg",
        },
        {
          playlistId : 4,
          artistName : "honey singh",
          songName : "birthday bash",
          audio : "Honey Singh/Birthday Bash.mp3",
          songPoster : "https://i.ytimg.com/vi/CiyAA_xraSo/maxresdefault.jpg",
        },
        {
          playlistId : 5,
          artistName : "honey singh",
          songName : "blue eyes",
          audio : "Honey Singh/Blue Eyes.mp3",
          songPoster : "https://i.ytimg.com/vi/_RhYmdUo6sg/maxresdefault.jpg",
        },
        {
          playlistId : 6,
          artistName : "honey singh",
          songName : "brown rang",
          audio : "Honey Singh/Brown Rang.mp3",
          songPoster : "https://i.ytimg.com/vi/BYIDm2K8RJc/maxresdefault.jpg",
        },
        {
          playlistId : 7,
          artistName : "honey singh",
          songName : "chaar botal vodka",
          audio : "Honey Singh/Chaar Botal Vodka.mp3",
          songPoster : "https://i.ytimg.com/vi/I3ckNdCgx2w/maxresdefault.jpg",
        },
        {
          playlistId : 8,
          artistName : "honey singh",
          songName : "chhote chhote peg",
          audio : "Honey Singh/Chhote Chhote Peg.mp3",
          songPoster : "https://i.ytimg.com/vi/xvYBg6MWPbM/maxresdefault.jpg",
        },
        {
          playlistId : 9,
          artistName : "honey singh",
          songName : "dope shope",
          audio : "Honey Singh/Dope Shope.mp3",
          songPoster : "https://i.ytimg.com/vi/usdMie3BGIk/maxresdefault.jpg",
        },
        {
          playlistId : 10,
          artistName : "honey singh",
          songName : "gatividhi",
          audio : "Honey Singh/Gatividhi.mp3",
          songPoster : "https://i.ytimg.com/vi/hZdfe7E1XR8/maxresdefault.jpg",
        },
      ],
    popularSongs :   
      [
        {
          popularsongId : 1,
          artistName : "honey singh",
          songName : "boom boom",
          audio : "Honey Singh/HoneyPopularSong/Boom Boom.mp3",
          songPoster : "https://i.ytimg.com/vi/yHg7kTnQCiA/maxresdefault.jpg",
        },
        {
          popularsongId : 2,
          artistName : "honey singh",
          songName : "dheere dheere",
          audio : "Honey Singh/HoneyPopularSong/Dheere Dheere.mp3",
          songPoster : "https://m.timesofindia.com/photo/71050196/size-144138/71050196.jpg",
        },
        {
          popularsongId : 3,
          artistName : "honey singh",
          songName : "dheeth",
          audio : "Honey Singh/HoneyPopularSong/Dheeth.mp3",
          songPoster : "https://i.ytimg.com/vi/z96REC6yQFs/maxresdefault.jpg",
        },
        {
          popularsongId : 4,
          artistName : "honey singh",
          songName : "dil chori",
          audio : "Honey Singh/HoneyPopularSong/Dil Chori.mp3",
          songPoster : "https://i.ytimg.com/vi/cRE_BH-6t6g/maxresdefault.jpg",
        },
        {
          popularsongId : 5,
          artistName : "honey singh",
          songName : "first kiss",
          audio : "Honey Singh/HoneyPopularSong/First Kiss.mp3",
          songPoster : "https://m.media-amazon.com/images/M/MV5BYjcwMjcxZWEtNzg4Ny00OTgwLTg1MTktYmU5OTI2YzQxZjc1XkEyXkFqcGdeQXVyMTYyMzk1MDk3._V1_FMjpg_UX1000_.jpg",
        },
        {
          popularsongId : 6,
          artistName : "honey singh",
          songName : "get up jawani",
          audio : "Honey Singh/HoneyPopularSong/Get Up Jawani.mp3",
          songPoster : "https://i.ytimg.com/vi/0Ry4xgZHMPU/maxresdefault.jpg",
        },
        {
          popularsongId : 7,
          artistName : "honey singh",
          songName : "kalaastar",
          audio : "Honey Singh/HoneyPopularSong/Kalaastar.mp3",
          songPoster : "https://i.ytimg.com/vi/rOouwTI6yAI/maxresdefault.jpg",
        },
        {
          popularsongId : 8,
          artistName : "honey singh",
          songName : "lashkare",
          audio : "Honey Singh/HoneyPopularSong/Lashkare.mp3",
          songPoster : "https://i.ytimg.com/vi/aQ78U8iXukk/maxresdefault.jpg",
        },
        {
          popularsongId : 9,
          artistName : "honey singh",
          songName : "loca",
          audio : "Honey Singh/HoneyPopularSong/Loca.mp3",
          songPoster : "https://i.ytimg.com/vi/BuZsBw4Wcdg/maxresdefault.jpg",
        },
        {
          popularsongId : 10,
          artistName : "honey singh",
          songName : "makhna",
          audio : "Honey Singh/HoneyPopularSong/Makhna.mp3",
          songPoster : "https://m.timesofindia.com/photo/67191678/size-200331/67191678.jpg",
        },
        {
          popularsongId : 11,
          artistName : "honey singh",
          songName : "melody roja",
          audio : "Honey Singh/HoneyPopularSong/Melody Roja.mp3",
          songPoster : "https://i.ytimg.com/vi/BFnfJn61gA4/maxresdefault.jpg",
        },
        {
          popularsongId : 12,
          artistName : "honey singh",
          songName : "note fenko",
          audio : "Honey Singh/HoneyPopularSong/Note Fenko.mp3",
          songPoster : "https://i.ytimg.com/vi/ccSOo5TOlvE/maxresdefault.jpg",
        },
        {
          popularsongId : 13,
          artistName : "honey singh",
          songName : "one bottle down",
          audio : "Honey Singh/HoneyPopularSong/One Bottle Down.mp3",
          songPoster : "https://i.ytimg.com/vi/Q8XYm12Wruk/maxresdefault.jpg",
        },
        {
          popularsongId : 14,
          artistName : "honey singh",
          songName : "pankhudi",
          audio : "Honey Singh/HoneyPopularSong/Pankhudi.mp3",
          songPoster : "https://www.5dariyanews.com/Uploads/2023/01/16/en-news-13565277-Pankhudi-large.jpg",
        },
        {
          popularsongId : 15,
          artistName : "honey singh",
          songName : "paris ka trip",
          audio : "Honey Singh/HoneyPopularSong/Paris Ka Trip.mp3",
          songPoster : "https://i.ytimg.com/vi/zM6s3JgF9_0/maxresdefault.jpg",
        },
        {
          popularsongId : 16,
          artistName : "honey singh",
          songName : "party all night",
          audio : "Honey Singh/HoneyPopularSong/Party All Night.mp3",
          songPoster : "https://i.ytimg.com/vi/uom_jWSs_44/maxresdefault.jpg",
        },
        {
          popularsongId : 17,
          artistName : "honey singh",
          songName : "party with the bhoothnath",
          audio : "Honey Singh/HoneyPopularSong/Party With The Bhoothnath.mp3",
          songPoster : "https://i.ytimg.com/vi/W7kdKf_aqX4/maxresdefault.jpg",
        },
        {
          popularsongId : 18,
          artistName : "honey singh",
          songName : "saiyaan ji",
          audio : "Honey Singh/HoneyPopularSong/Saiyaan Ji.mp3",
          songPoster : "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2021/01/saiyaan-ji-1611745475.jpg",
        },
        {
          popularsongId : 19,
          artistName : "honey singh",
          songName : "shor machega",
          audio : "Honey Singh/HoneyPopularSong/Shor Machega.mp3",
          songPoster : "https://i.ytimg.com/vi/5G2y80X6s6g/maxresdefault.jpg",
        },
        {
          popularsongId : 20,
          artistName : "honey singh",
          songName : "yaar naa miley",
          audio : "Honey Singh/HoneyPopularSong/Yaar Naa Miley.mp3",
          songPoster : "https://downloads4djs.co.in/wp-content/uploads/2014/07/YAAR-NA-MILEY-1024x621.jpg",
        },
      ]
  },

  {
    id : 5,
    artist : "Himesh Reshammiya",
    photo : "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201909/_YIM6743.jpeg?size=690:388",
    artistPhoto : himesh,
    about : "Himesh Reshammiya is an Indian playback singer, music director, songwriter, film & music producer and actor in Hindi cinema.",
    playLists:
      [
        {
          playlistId : 1,
          artistName : "himesh reshammiya",
          songName : "aaj unse milna hai",
          audio : "Himesh Reshammiya/Aaj Unse Milna Hai.mp3",
          songPoster : "https://i.ytimg.com/vi/9Vy9ObEOVvg/maxresdefault.jpg",
        },
        {
          playlistId : 2,
          artistName : "himesh reshammiya",
          songName : "aap ki khatir",
          audio : "Himesh Reshammiya/Aap Ki Khatir.mp3",
          songPoster : "https://i.ytimg.com/vi/j3ixqwdXTC0/maxresdefault.jpg",
        },
        {
          playlistId : 3,
          artistName : "himesh reshammiya",
          songName : "aashiq banaya aapne",
          audio : "Himesh Reshammiya/Aashiq Banaya Aapne.mp3",
          songPoster : "https://i.ytimg.com/vi/YCHoTQ-epsE/maxresdefault.jpg",
        },
        {
          playlistId : 4,
          artistName : "himesh reshammiya",
          songName : "aashiqui meri",
          audio : "Himesh Reshammiya/Aashiqui Meri.mp3",
          songPoster : "https://i.ytimg.com/vi/wJe85HOuYTo/maxresdefault.jpg",
        },
        {
          playlistId : 5,
          artistName : "himesh reshammiya",
          songName : "afsana",
          audio : "Himesh Reshammiya/Afsana.mp3",
          songPoster : "https://i.ytimg.com/vi/psaBpso9BG4/maxresdefault.jpg",
        },
        {
          playlistId : 6,
          artistName : "himesh reshammiya",
          songName : "baby tujhe paap lagega",
          audio : "Himesh Reshammiya/Baby Tujhe Paap Lagega.mp3",
          songPoster : "https://m.timesofindia.com/photo/102985544/size-192619/102985544.jpg",
        },
        {
          playlistId : 7,
          artistName : "himesh reshammiya",
          songName : "bekhudi",
          audio : "Himesh Reshammiya/Bekhudi.mp3",
          songPoster : "https://i.ytimg.com/vi/MZxo9CDAAtw/maxresdefault.jpg",
        },
        {
          playlistId : 8,
          artistName : "himesh reshammiya",
          songName : "bodyguard",
          audio : "Himesh Reshammiya/Bodyguard.mp3",
          songPoster : "https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/old_images/MOVIE/5771/1000065771/1000065771-h",
        },
        {
          playlistId : 9,
          artistName : "himesh reshammiya",
          songName : "chalao na naino se",
          audio : "Himesh Reshammiya/Chalao Na Naino Se.mp3",
          songPoster : "https://blastatrumpet.files.wordpress.com/2012/07/bol_bachchan_poster.jpg",
        },
        {
          playlistId : 10,
          artistName : "himesh reshammiya",
          songName : "chura liyaa hai",
          audio : "Himesh Reshammiya/Chura Liyaa Hai.mp3",
          songPoster : "https://i.ytimg.com/vi/RyPjXuPBCAc/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBDDc0lVEkpCK_NxI2YHcS0hqRXwg",
        },
      ],
    popularSongs :   
      [
        {
          popularsongId : 1,
          artistName : "himesh reshammiya",
          songName : "cutie pie",
          audio : "Himesh Reshammiya/HimeshPopularSong/Cutie Pie.mp3",
          songPoster : "https://i.ytimg.com/vi/oK5jrObWlWQ/maxresdefault.jpg",
        },
        {
          popularsongId : 2,
          artistName : "himesh reshammiya",
          songName : "damadamm",
          audio : "Himesh Reshammiya/HimeshPopularSong/Damadamm.mp3",
          songPoster : "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/89/d6/85/89d68506-ad89-909a-5dce-6406b1f80b5c/8902894697040_cover.jpg/600x600bf-60.jpg",
        },
        {
          popularsongId : 3,
          artistName : "himesh reshammiya",
          songName : "dard dilo ke",
          audio : "Himesh Reshammiya/HimeshPopularSong/Dard Dilo Ke.mp3",
          songPoster : "https://i.ytimg.com/vi/CExS4CBufng/maxresdefault.jpg",
        },
        {
          popularsongId : 4,
          artistName : "himesh reshammiya",
          songName : "dekhoon tujhe to",
          audio : "Himesh Reshammiya/HimeshPopularSong/Dekhoon Tujhe To.mp3",
          songPoster : "https://i.ytimg.com/vi/fJE4tn6a07g/maxresdefault.jpg",
        },
        {
          popularsongId : 5,
          artistName : "himesh reshammiya",
          songName : "dil disco karein",
          audio : "Himesh Reshammiya/HimeshPopularSong/Dil Disco Karein.mp3",
          songPoster : "https://media.lyricsmint.com/photos/20000/maxresdefault-30_cover.jpg",
        },
        {
          popularsongId : 6,
          artistName : "himesh reshammiya",
          songName : "ek number",
          audio : "Himesh Reshammiya/HimeshPopularSong/Ek Number.mp3",
          songPoster : "https://i.ytimg.com/vi/l3pKT6hoVXk/maxresdefault.jpg",
        },
        {
          popularsongId : 7,
          artistName : "himesh reshammiya",
          songName : "ek tum hi",
          audio : "Himesh Reshammiya/HimeshPopularSong/Ek Tum Hi.mp3",
          songPoster : "https://i.ytimg.com/vi/Ee9N4cepOR0/maxresdefault.jpg",
        },
        {
          popularsongId : 8,
          artistName : "himesh reshammiya",
          songName : "ganpati gajaanann",
          audio : "Himesh Reshammiya/HimeshPopularSong/Ganpati Gajaanann.mp3",
          songPoster : "https://i.ytimg.com/vi/ZapdpJsT44o/hqdefault.jpg",
        },
        {
          popularsongId : 9,
          artistName : "himesh reshammiya",
          songName : "hari om hari om",
          audio : "Himesh Reshammiya/HimeshPopularSong/Hari Om Hari Om.mp3",
          songPoster : "https://i.ytimg.com/vi/mQ1iIFuaOR8/maxresdefault.jpg",
        },
        {
          popularsongId : 10,
          artistName : "himesh reshammiya",
          songName : "heer tu meri",
          audio : "Himesh Reshammiya/HimeshPopularSong/Heer Tu Meri.mp3",
          songPoster : "https://i.ytimg.com/vi/dLk-UWHLB0s/maxresdefault.jpg",
        },
        {
          popularsongId : 11,
          artistName : "himesh reshammiya",
          songName : "hookah bar",
          audio : "Himesh Reshammiya/HimeshPopularSong/Hookah Bar.mp3",
          songPoster : "https://i.ytimg.com/vi/HYzLpk6gPt0/maxresdefault.jpg",
        },
        {
          popularsongId : 12,
          artistName : "himesh reshammiya",
          songName : "hum pagal nahi hai",
          audio : "Himesh Reshammiya/HimeshPopularSong/Hum Pagal Nahi Hai.mp3",
          songPoster : "https://i.ytimg.com/vi/hl8SFOD2AcQ/maxresdefault.jpg",
        },
        {
          popularsongId : 13,
          artistName : "himesh reshammiya",
          songName : "jave saari duniya",
          audio : "Himesh Reshammiya/HimeshPopularSong/Jave Saari Duniya.mp3",
          songPoster : "https://i.ytimg.com/vi/LQv96sR5G7A/maxresdefault.jpg",
        },
        {
          popularsongId : 14,
          artistName : "himesh reshammiya",
          songName : "jhalak dikhla ja",
          audio : "Himesh Reshammiya/HimeshPopularSong/Jhalak Dikhla Ja.mp3",
          songPoster : "https://i.ytimg.com/vi/RgLq1LRlISE/maxresdefault.jpg",
        },
        {
          popularsongId : 15,
          artistName : "himesh reshammiya",
          songName : "jhoom jhoom",
          audio : "Himesh Reshammiya/HimeshPopularSong/Jhoom Jhoom.mp3",
          songPoster : "https://i.ytimg.com/vi/TMiHf8b4fCA/maxresdefault.jpg",
        },
        {
          popularsongId : 16,
          artistName : "himesh reshammiya",
          songName : "jhoot nahinbolna",
          audio : "Himesh Reshammiya/HimeshPopularSong/Jhoot Nahin Bolna.mp3",
          songPoster : "https://i0.wp.com/www.hindiadda.com/wp-content/uploads/ha/2020/03/Tere-Bina-Lyrics-scaled.jpg?fit=1024%2C576&ssl=1",
        },
        {
          popularsongId : 17,
          artistName : "himesh reshammiya",
          songName : "jumme ki raat",
          audio : "Himesh Reshammiya/HimeshPopularSong/Jumme Ki Raat.mp3",
          songPoster : "https://i.ytimg.com/vi/zHPvJrfti4A/maxresdefault.jpg",
        },
        {
          popularsongId : 18,
          artistName : "himesh reshammiya",
          songName : "kajra kajra kajraare",
          audio : "Himesh Reshammiya/HimeshPopularSong/Kajra Kajra Kajraare.mp3",
          songPoster : "https://i.ytimg.com/vi/oELF0NoLQeg/maxresdefault.jpg",
        },
        {
          popularsongId : 19,
          artistName : "himesh reshammiya",
          songName : "keeda",
          audio : "Himesh Reshammiya/HimeshPopularSong/Keeda.mp3",
          songPoster : "https://i.ytimg.com/vi/YYDf_E9oBsA/maxresdefault.jpg",
        },
        {
          popularsongId : 20,
          artistName : "himesh reshammiya",
          songName : "lonely",
          audio : "Himesh Reshammiya/HimeshPopularSong/Lonely.mp3",
          songPoster : "https://i.ytimg.com/vi/OCDyLdZSxYw/maxresdefault.jpg",
        },
      ]
  },

  {
    id : 6,
    artist : "Neha Kakkar",
    photo : "https://www.prokerala.com/news/photos/imgs/1200/pune-singer-neha-kakkar-performing-at-a-college-264595.jpg",
    artistPhoto : neha,
    about : "Neha Kakkar Singh, is an Indian playback singer. She is the younger sister of playback singers Tony Kakkar and Sonu Kakkar. She began performing at a very early age at religious events.",
    playLists:
      [
        {
          playlistId : 1,
          artistName : "neha kakkar",
          songName : "12 ladke",
          audio : "Neha Kakkar/12 Ladke.mp3",
          songPoster : "https://i.ytimg.com/vi/VU11sBEdEns/maxresdefault.jpg",
        },
        {
          playlistId : 2,
          artistName : "neha kakkar",
          songName : "aa to sahii",
          audio : "Neha Kakkar/Aa To Sahii.mp3",
          songPoster : "https://i.ytimg.com/vi/Js4Xx-hzkIU/maxresdefault.jpg",
        },
        {
          playlistId : 3,
          artistName : "neha kakkar",
          songName : "aashiq banaya aapne",
          audio : "Neha Kakkar/Aashiq Banaya Aapne.mp3",
          songPoster : "https://i.ytimg.com/vi/zNMGiMg75zg/maxresdefault.jpg",
        },
        {
          playlistId : 4,
          artistName : "neha kakkar",
          songName : "badri ki dulhania",
          audio : "Neha Kakkar/Badri Ki Dulhania.mp3",
          songPoster : "https://s1.dmcdn.net/v/J6ZwI1P14TxYINrnW/x480",
        },
        {
          playlistId : 5,
          artistName : "neha kakkar",
          songName : "bheegi bheegi",
          audio : "Neha Kakkar/Bheegi Bheegi.mp3",
          songPoster : "https://i.ytimg.com/vi/9HDuBa5m8AA/maxresdefault.jpg",
        },
        {
          playlistId : 6,
          artistName : "neha kakkar",
          songName : "chad gayi chad gayi",
          audio : "Neha Kakkar/Chad Gayi Chad Gayi.mp3",
          songPoster : "https://i.ytimg.com/vi/yFJc8Cl-0G4/maxresdefault.jpg",
        },
        {
          playlistId : 7,
          artistName : "neha kakkar",
          songName : "chalti hai kya",
          audio : "Neha Kakkar/Chalti Hai Kya.mp3",
          songPoster : "https://i.ytimg.com/vi/gG6l6D7ahe0/maxresdefault.jpg",
        },
        {
          playlistId : 8,
          artistName : "neha kakkar",
          songName : "coca cola",
          audio : "Neha Kakkar/Coca Cola.mp3",
          songPoster : "https://i.ytimg.com/vi/YMuTloL20O0/maxresdefault.jpg",
        },
        {
          playlistId : 9,
          artistName : "neha kakkar",
          songName : "daiyya daiyya",
          audio : "Neha Kakkar/Daiyya Daiyya.mp3",
          songPoster : "https://i.ytimg.com/vi/fJLtjr3sXlk/maxresdefault.jpg",
        },
        {
          playlistId : 10,
          artistName : "neha kakkar",
          songName : "dekhega raja trailer",
          audio : "Neha Kakkar/Dekhega Raja Trailer.mp3",
          songPoster : "https://i.ytimg.com/vi/iJzZ5XH0VhQ/maxresdefault.jpg",
        },
      ],
    popularSongs :   
      [
        {
          popularsongId : 1,
          artistName : "neha kakkar",
          songName : "bol kaffara kya hoga",
          audio : "Neha Kakkar/NehaPopularSong/Bol Kaffara Kya Hoga.mp3",
          songPoster : "https://i.ytimg.com/vi/PAqx35UPV_k/maxresdefault.jpg",
        },
        {
          popularsongId : 2,
          artistName : "neha kakkar",
          songName : "buhe vich",
          audio : "Neha Kakkar/NehaPopularSong/Buhe Vich.mp3",
          songPoster : "https://i.ytimg.com/vi/Y1D-P0k3xEc/maxresdefault.jpg",
        },
        {
          popularsongId : 3,
          artistName : "neha kakkar",
          songName : "dholida",
          audio : "Neha Kakkar/NehaPopularSong/Dholida.mp3",
          songPoster : "https://i.ytimg.com/vi/dvkZmsqrSRw/maxresdefault.jpg",
        },
        {
          popularsongId : 4,
          artistName : "neha kakkar",
          songName : "dil bechara",
          audio : "Neha Kakkar/NehaPopularSong/Dil Bechara.mp3",
          songPoster : "https://i.ytimg.com/vi/OD1LhUu4bRI/maxresdefault.jpg",
        },
        {
          popularsongId : 5,
          artistName : "neha kakkar",
          songName : "dil chahiye",
          audio : "Neha Kakkar/NehaPopularSong/Dil Chahiye.mp3",
          songPoster : "https://i.ytimg.com/vi/OxpsUrMfYOI/maxresdefault.jpg",
        },
        {
          popularsongId : 6,
          artistName : "neha kakkar",
          songName : "dil ko karaar",
          audio : "Neha Kakkar/NehaPopularSong/Dil Ko Karaar.mp3",
          songPoster : "https://i.ytimg.com/vi/mn8ywyrgPwQ/maxresdefault.jpg",
        },
        {
          popularsongId : 7,
          artistName : "neha kakkar",
          songName : "dilbar",
          audio : "Neha Kakkar/NehaPopularSong/Dilbar.mp3",
          songPoster : "https://i.ytimg.com/vi/TRa9IMvccjg/maxresdefault.jpg",
        },
        {
          popularsongId : 8,
          artistName : "neha kakkar",
          songName : "do gallan",
          audio : "Neha Kakkar/NehaPopularSong/Do Gallan.mp3",
          songPoster : "https://i.ytimg.com/vi/3bFOs6Xbjho/maxresdefault.jpg",
        },
        {
          popularsongId : 9,
          artistName : "neha kakkar",
          songName : "do peg maar",
          audio : "Neha Kakkar/NehaPopularSong/Do Peg Maar.mp3",
          songPoster : "https://i.ytimg.com/vi/GYbPrev2aQU/maxresdefault.jpg",
        },
        {
          popularsongId : 10,
          artistName : "neha kakkar",
          songName : "dono ke dono",
          audio : "Neha Kakkar/NehaPopularSong/Dono Ke Dono.mp3",
          songPoster : "https://i.ytimg.com/vi/jibXCFbHJvM/maxresdefault.jpg",
        },
        {
          popularsongId : 11,
          artistName : "neha kakkar",
          songName : "ek do teen chaar",
          audio : "Neha Kakkar/NehaPopularSong/Ek Do Teen Chaar.mp3",
          songPoster : "https://i.ytimg.com/vi/qtoKAwoxZpg/maxresdefault.jpg",
        },
        {
          popularsongId : 12,
          artistName : "neha kakkar",
          songName : "ek toh kum zindagani",
          audio : "Neha Kakkar/NehaPopularSong/Ek Toh Kum Zindagani.mp3",
          songPoster : "https://i.ytimg.com/vi/hl8SFOD2AcQ/maxresdefault.jpg",
        },
        {
          popularsongId : 13,
          artistName : "neha kakkar",
          songName : "gali gali",
          audio : "Neha Kakkar/NehaPopularSong/Gali Gali.mp3",
          songPoster : "https://m.timesofindia.com/photo/67071969/size-126403/67071969.jpg",
        },
        {
          popularsongId : 14,
          artistName : "neha kakkar",
          songName : "ghungta",
          audio : "Neha Kakkar/NehaPopularSong/Ghungta.mp3",
          songPoster : "https://i.ytimg.com/vi/BthPzs1GBrs/maxresdefault.jpg",
        },
        {
          popularsongId : 15,
          artistName : "neha kakkar",
          songName : "humne pee rakhi ha",
          audio : "Neha Kakkar/NehaPopularSong/Humne Pee Rakhi Ha.mp3",
          songPoster : "https://i.ytimg.com/vi/_mmVjaYnc5I/maxresdefault.jpg",
        },
        {
          popularsongId : 16,
          artistName : "neha kakkar",
          songName : "jadoo ki jhappi",
          audio : "Neha Kakkar/NehaPopularSong/Jadoo Ki Jhappi.mp3",
          songPoster : "https://i.ytimg.com/vi/eO5H2LIPDzc/maxresdefault.jpg",
        },
        {
          popularsongId : 17,
          artistName : "neha kakkar",
          songName : "khoobsurat",
          audio : "Neha Kakkar/NehaPopularSong/Khoobsurat.mp3",
          songPoster : "https://i.ytimg.com/vi/VhLHRnk3AyM/maxresdefault.jpg",
        },
        {
          popularsongId : 18,
          artistName : "neha kakkar",
          songName : "khyaal rakhya kar",
          audio : "Neha Kakkar/NehaPopularSong/Khyaal Rakhya Kar.mp3",
          songPoster : "https://i.ytimg.com/vi/pEO2a7QzXqQ/maxresdefault.jpg",
        },
        {
          popularsongId : 19,
          artistName : "neha kakkar",
          songName : "kudiya shehar diyan",
          audio : "Neha Kakkar/NehaPopularSong/Kudiya Shehar Diyan.mp3",
          songPoster : "https://i.ytimg.com/vi/HXX4xkPn8Tk/maxresdefault.jpg",
        },
        {
          popularsongId : 20,
          artistName : "neha kakkar",
          songName : "la la la",
          audio : "Neha Kakkar/NehaPopularSong/La La La.mp3",
          songPoster : "https://i.ytimg.com/vi/9sQkjMgFglY/maxresdefault.jpg",
        },
      ]
  },

];

export default MusicData;